'use client';
import { useState, useEffect, useCallback } from 'react';
import axios from 'axios';
import {
  FiUsers,
  FiDollarSign,
  FiZap,
  FiActivity,
  FiPieChart,
  FiTrendingUp,
  FiLayers,
  FiShield,
  FiEye,
  FiMousePointer,
  FiClock,
  FiAlertCircle,
  FiRefreshCw,
  FiInfo,
} from 'react-icons/fi';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from 'recharts';

const api = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_BASE_URL,
  withCredentials: true,
});

const CACHE_KEY = 'admin_stats_cache';
const CACHE_TIME_KEY = 'admin_stats_time';
const ONE_DAY = 5 * 60 * 1000; // 5 minutes for testing, change to 24 * 60 * 60 * 1000 for production

export default function AdminDashboard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState(null);

  const fetchStats = useCallback(async (force = false) => {
    try {
      if (!force) setLoading(true);
      else setRefreshing(true);

      const cachedData = localStorage.getItem(CACHE_KEY);
      const lastCachedTime = localStorage.getItem(CACHE_TIME_KEY);
      const now = new Date().getTime();

      // ক্যাশ লজিক: যদি ফোর্স না করা হয় এবং ক্যাশ ভ্যালিড থাকে
      if (!force && cachedData && lastCachedTime && now - lastCachedTime < ONE_DAY) {
        setData(JSON.parse(cachedData));
        setLoading(false);
        return;
      }

      const { data: response } = await api.get('/api/admin/stats');

      if (response.success) {
        setData(response);
        localStorage.setItem(CACHE_KEY, JSON.stringify(response));
        localStorage.setItem(CACHE_TIME_KEY, now.toString());
        console.log(response);
        setError(null);
      } else {
        setError('Failed to fetch stats');
      }
    } catch (err) {
      console.error('Dashboard Stats Error:', err);
      setError('Connection to server failed');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    fetchStats();
  }, [fetchStats]);

  if (loading)
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4">
        <div className="w-8 h-8 border-2 border-orange-500 border-t-transparent rounded-full animate-spin"></div>
        <p className="text-[10px] font-black uppercase tracking-widest text-gray-400">
          Loading Intelligence...
        </p>
      </div>
    );

  if (error)
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-red-500 gap-2">
        <FiAlertCircle size={24} />
        <p className="text-xs font-black uppercase tracking-widest">{error}</p>
        <button
          onClick={() => fetchStats(true)}
          className="mt-4 px-4 py-2 bg-orange-500 text-white text-[10px] font-black uppercase rounded-lg"
        >
          Try Again
        </button>
      </div>
    );

  const { cards, charts } = data;

  const revenueNum = parseFloat(cards.totalRevenue) || 0;
  const netProfitNum = parseFloat(cards.netProfit) || 0;
  const stripeFeesNum = parseFloat(cards.stripeFees) || 0;

  const profitMargin = revenueNum > 0 ? ((netProfitNum / revenueNum) * 100).toFixed(1) : '0.0';
  const feeImpact = revenueNum > 0 ? ((stripeFeesNum / revenueNum) * 100).toFixed(1) : '0.0';

  const mainMetrics = [
    {
      label: 'Total Revenue',
      value: `€${cards.totalRevenue}`,
      icon: FiDollarSign,
      sub: 'Lifetime Gross',
      color: 'bg-orange-600',
      description:
        'Gross Capital: Total funds processed through the gateway before any deductions or fees.',
    },
    {
      label: 'Net Earned Revenue',
      value: `€${cards.netEarnedRevenue}`,
      icon: FiTrendingUp,
      sub: 'Non-refundable Earned',
      color: 'bg-emerald-600',
      description:
        'Earned Liquidity: Realized revenue from completed promotions that is no longer subject to refunds.',
    },
    {
      label: 'Total Clicks',
      value: cards.totalClicks,
      icon: FiMousePointer,
      sub: 'Analytics Sync',
      color: 'bg-blue-600',
      description:
        'Traffic Node: Cumulative interaction count across all PPC campaigns currently in the system.',
    },
    {
      label: 'Total Views',
      value: cards.totalViews,
      icon: FiEye,
      sub: 'Global Reach',
      color: 'bg-purple-600',
      description:
        'Network Visibility: Total impression logs generated by the discovery engine for all approved listings.',
    },
    {
      label: 'Active Promotions',
      value: cards.activePromotions,
      icon: FiZap,
      sub: 'PPC & Boost Live',
      color: 'bg-green-600',
      description:
        'Active Protocols: The number of promotional campaigns currently drawing from creator wallets.',
    },
  ];

  const secondaryMetrics = [
    {
      label: 'Net Profit',
      value: `€${cards.netProfit || 0}`,
      icon: FiTrendingUp,
      trend: 'Post Tax & Fees',
      isHighlight: true,
    },
    {
      label: 'Stripe Fees',
      value: `€${cards.stripeFees || 0}`,
      icon: FiActivity,
      trend: 'Estimated Cost',
    },
    {
      label: 'VAT Liability',
      value: `€${cards.totalVat || 0}`,
      icon: FiShield,
      trend: 'Total Tax',
    },
    { label: 'Payments', value: cards.recentPayments, icon: FiClock, trend: 'Last 24 Hours' },
    {
      label: 'Creators',
      value: cards.totalCreators || 0,
      icon: FiUsers,
      trend: 'Approved Partners',
    },
    // {
    //   label: 'Pending Creators',
    //   value: cards.pendingCreatorRequests || 0,
    //   icon: FiShield,
    //   trend: 'Review Required',
    //   isWarning: cards.pendingCreatorRequests > 0,
    // },
    {
      label: 'Pending Listings',
      value: cards.pendingListings || 0,
      icon: FiLayers,
      trend: 'Manual Review',
      isWarning: cards.pendingListings > 0,
    },
  ];

  return (
    <div className="space-y-8 animate-in fade-in duration-700 font-sans">
      {/* --- Header --- */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div className="flex items-center gap-4">
          <h2 className="text-3xl font-black uppercase tracking-tighter italic dark:text-white">
            Admin <span className="text-orange-500">Overview</span>
          </h2>
          <button
            onClick={() => fetchStats(true)}
            disabled={refreshing}
            className={`p-2 rounded-lg bg-gray-100 dark:bg-white/5 text-gray-400 hover:text-orange-500 transition-all ${refreshing ? 'animate-spin text-orange-500' : ''}`}
            title="Refresh Intelligence"
          >
            <FiRefreshCw size={16} />
          </button>
        </div>
        <div className="px-4 py-2 bg-gray-50 dark:bg-white/5 border border-gray-100 dark:border-white/10 rounded text-[9px] font-black uppercase tracking-widest text-gray-500 flex items-center gap-2">
          <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse"></span>
          Data Integrity Verified:{' '}
          {new Date(parseInt(localStorage.getItem(CACHE_TIME_KEY))).toLocaleTimeString()}
        </div>
      </div>

      {/* --- 1. Top 4 Priority Cards --- */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
        {mainMetrics.map((card, i) => (
          <div
            key={i}
            className={`${card.color} p-6 rounded-xl text-white shadow-xl shadow-black/5 relative group transition-all hover:-translate-y-1`}
          >
            {/* Icon Mask to prevent tooltip cut-off */}
            <div className="absolute inset-0 rounded-xl overflow-hidden pointer-events-none">
              <card.icon
                className="absolute -right-4 -bottom-4 opacity-20 group-hover:scale-110 transition-transform"
                size={100}
              />
            </div>

            <div className="relative z-10">
              <div className="flex items-center gap-2 mb-1">
                <p className="text-[10px] font-black uppercase tracking-widest opacity-70">
                  {card.label}
                </p>
                <div className="relative group/info">
                  <FiInfo size={10} className="opacity-50 hover:opacity-100 cursor-help" />
                  <div className="absolute bottom-full left-0 mb-2 w-48 p-2 bg-zinc-900 text-[9px] text-zinc-300 rounded-lg opacity-0 group-hover/info:opacity-100 transition-opacity pointer-events-none shadow-2xl border border-white/10 z-[100] normal-case tracking-normal font-medium">
                    {card.description}
                  </div>
                </div>
              </div>
              <h3 className="text-3xl font-black mt-1 italic tracking-tighter">{card.value}</h3>
              <p className="text-[9px] mt-4 font-bold uppercase tracking-widest opacity-80">
                {card.sub}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* --- 2. Financial & Meta Grid --- */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-4">
        {secondaryMetrics.map((card, i) => (
          <div
            key={i}
            className={`bg-white dark:bg-[#0c0c0c] border ${card.isWarning ? 'border-red-500/50 bg-red-500/5' : 'border-gray-100 dark:border-white/10'} p-4 rounded-lg transition-all hover:border-orange-500/30`}
          >
            <div className="flex items-center gap-2 mb-3">
              <card.icon
                className={
                  card.isHighlight
                    ? 'text-orange-500'
                    : card.isWarning
                      ? 'text-red-500'
                      : 'text-gray-400'
                }
                size={14}
              />
              <span className="text-[9px] font-black uppercase tracking-widest text-gray-400">
                {card.label}
              </span>
            </div>
            <h4
              className={`text-lg font-black tracking-tighter italic ${card.isHighlight ? 'text-orange-500' : card.isWarning ? 'text-red-500' : 'dark:text-white'}`}
            >
              {card.value}
            </h4>
            <p className="text-[8px] font-bold text-gray-500 uppercase mt-1 tracking-tighter">
              {card.trend}
            </p>
          </div>
        ))}
      </div>

      {/* --- 3. Charts Section --- */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-8 bg-white dark:bg-[#0c0c0c] rounded-xl border border-gray-100 dark:border-white/5 py-6 pr-6 shadow-sm">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-10 pl-6">
            <h3 className="text-xl font-black italic uppercase tracking-tighter dark:text-white">
              Revenue <span className="text-orange-500">&</span> Profit{' '}
              <span className="text-gray-400 text-[10px] font-black ml-2 tracking-widest bg-gray-100 dark:bg-white/5 px-2 py-1 rounded uppercase">
                7 Day Performance
              </span>
            </h3>
            <div className="flex gap-4">
              <LegendItem color="bg-orange-500" label="Revenue" />
              <LegendItem color="bg-green-500" label="Net Profit" />
            </div>
          </div>
          <div className="h-87.5 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={charts.revenueFlow}>
                <defs>
                  <linearGradient id="colorRev" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#f97316" stopOpacity={0.15} />
                    <stop offset="95%" stopColor="#f97316" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#88888810" />
                <XAxis
                  dataKey="date"
                  axisLine={false}
                  tickLine={false}
                  tick={{ fontSize: 9, fontWeight: 900, fill: '#666' }}
                  dy={10}
                />
                <YAxis
                  axisLine={false}
                  tickLine={false}
                  tick={{ fontSize: 9, fontWeight: 900, fill: '#666' }}
                  tickFormatter={(val) => `€${val}`}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#0c0c0c',
                    border: '1px solid #333',
                    borderRadius: '8px',
                    fontSize: '10px',
                    fontWeight: '800',
                  }}
                />
                <Area
                  type="monotone"
                  dataKey="revenue"
                  stroke="#f97316"
                  strokeWidth={4}
                  fill="url(#colorRev)"
                  animationDuration={1500}
                />
                <Area
                  type="monotone"
                  dataKey="profit"
                  stroke="#22c55e"
                  strokeWidth={4}
                  fill="transparent"
                  strokeDasharray="5 5"
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="lg:col-span-4 bg-white dark:bg-[#0c0c0c] rounded-xl border border-gray-100 dark:border-white/5 p-6 flex flex-col justify-between shadow-sm">
          <div>
            <h3 className="text-[10px] font-black uppercase tracking-[0.3em] text-gray-400 mb-8 flex items-center gap-2">
              <FiPieChart className="text-orange-500" /> Margin Analysis
            </h3>
            <div className="space-y-6">
              <StatBlock
                label="Gross Profit Margin"
                value={`${profitMargin}%`}
                color="text-green-500"
              />
              <StatBlock label="Stripe Fee Impact" value={`${feeImpact}%`} color="text-red-500" />
              <StatBlock label="VAT Liability" value={`€${cards.totalVat}`} color="text-blue-500" />
            </div>
          </div>
          <div className="mt-8 p-4 bg-orange-500/5 border border-orange-500/10 rounded-lg">
            <p className="text-[9px] font-black uppercase text-orange-500 tracking-widest mb-1">
              Business Health
            </p>
            <p className="text-[11px] text-gray-500 leading-relaxed italic font-medium">
              System calculates Stripe fees at{' '}
              <span className="text-orange-500 font-bold">2.9% + 0.30€</span>. Net margin is
              healthy.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

const LegendItem = ({ color, label }) => (
  <div className="flex items-center gap-2">
    <div className={`w-2 h-2 rounded-full ${color}`}></div>
    <span className="text-[9px] font-black text-gray-400 uppercase tracking-widest">{label}</span>
  </div>
);

const StatBlock = ({ label, value, color }) => (
  <div className="group cursor-default">
    <p className="text-[9px] font-black uppercase tracking-widest text-gray-500 mb-1 group-hover:text-orange-500 transition-colors">
      {label}
    </p>
    <p className={`text-2xl font-black italic tracking-tighter ${color}`}>{value}</p>
  </div>
);
